# Adapt to your own Zotero library
library_id: ???
api_token: ???
ignored_collections: []

# Leave untouched
paper_types: ['bookSection', 'conferencePaper', 'journalArticle', 'report']
venue_keys_per_type:
    bookSection: ['bookTitle']
    conferencePaper: ['proceedingsTitle', 'conferenceName']
    journalArticle: ['publicationTitle', 'journalAbbreviation']
    report: []

# Switch to trigger the upload
upload: False
