VENUES = {
    'iccv': 'ICCV',
    'international conference on computer vision': 'ICCV',
    'cvpr': 'CVPR',
    'conference on computer vision and pattern recognition': 'CVPR',
    'eccv': 'ECCV',
    'european conference on computer vision': 'ECCV',
    'accv': 'ACCV',
    'asian conference on computer vision': 'ACCV',
    'neurips': 'NeurIPS',
    'nips': 'NeurIPS',
    'neural information processing systems': 'NeurIPS',
    'bmvc': 'BMVC',
    'british machine vision conference': 'BMVC',
    '3dv': '3DV',
    'international conference on 3d vision': '3DV',
    'iclr': 'ICLR',
    'international conference on learning representations': 'ICLR',
    'icml': 'ICML',
    'international conference on machine learning': 'ICML',
    'tpami': 'TPAMI',
    'transactions on pattern analysis and machine intelligence': 'TPAMI',
    'ijcv': 'IJCV',
    'international journal of computer vision': 'IJCV',
    'cviu': 'CVIU',
    'computer vision and image understanding': 'CVIU',
    'tog': 'TOG',
    'transactions on graphics': 'TOG'
}
