# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - notion: default.yaml
  - proxy: default.yaml
  - zotero: default.yaml

url: null
id: null
verbose: True
