#!/bin/bash

: '
This script will add the `nora/scripts/` directory to your PATH
environment variable in your .bashrc file. Running this will then allow
calling `nora` from anywhere on your machine, without the need to
manually activate the conda environment and navigate to the project
folder.
  ```bash
  nora ...
  ```
'

# Recover the NoRA project's directory from the position of the script
# and move there
NORA_SCRIPT_DIR=`realpath $(dirname $0)`

# Define the line to be added to .bashrc
LINE="export PATH=\$PATH:$NORA_SCRIPT_DIR"

# Function to check if a path is already in the PATH variable
is_path_in_path() {
    local path_to_check="$1"
    echo "$PATH" | tr ':' '\n' | grep -Fxq "$path_to_check"
}

# Add the line to .bashrc if it is not already present
if ! is_path_in_path "$SCRIPT_DIR"; then
    if ! grep -Fxq "$LINE" ~/.bashrc; then
        echo "" >> ~/.bashrc
        echo "# added by NoRA installer" >> ~/.bashrc
        echo "$LINE" >> ~/.bashrc
        echo "Added $NORA_SCRIPT_DIR to PATH in ~/.bashrc"
    else
        echo "$NORA_SCRIPT_DIR is already in the PATH"
    fi
else
    echo "$NORA_SCRIPT_DIR is already in the PATH"
fi
