#!/bin/bash

: '
This script is made to facilitate using NoRA tools by simply
calling from anywhere on your machine:
  ```bash
  nora ...
  ```
without the need to activate the conda environment and navigate
to the project folder.

To make this work on any UNIX-based platform, you will need to run the
following script first:
  ```bash
  nora/scripts/add_nora_to_path_unix
  ```
'

# conda installation directory
CONDA_DIR=`conda info --all | sed -n 's/^CONDA_ROOT: \(.*\)$/\1/p'`

# Recover the NoRA project's directory from the position of the script
# and move there
NORA_DIR=`dirname $(realpath $(dirname $0))`
cd $NORA_DIR

# Activate the nora conda environment
source ${CONDA_DIR}/etc/profile.d/conda.sh
conda activate nora

# Run the command
python nora.py $@
