verbose: True

notion:
    # See https://developers.notion.com/docs/create-a-notion-integration
    token: ???
    papers_db_id: ???
    people_db_id: ???
    affiliations_db_id: ???
    venues_db_id: ???
    topics_db_id: ???

    # If you happen to modify your field names in Notion, update the
    # following database-specific keys
    person_keys:
        name: 'Name'
        affiliations: '🏢 Affiliations'
        papers: '📜 Papers'
        website: 'Website'

    paper_keys:
        name: 'Name'
        authors: '👤 Authors'
        abstract: 'Abstract'
        topics: '🧲 Key topics'
        url: 'URL'
        to_read: 'Reading status'
        year: 'Year'
        venue: '🤹 Venue'

    affiliation_keys:
        name: 'Name'

    venue_keys:
        name: 'Name'

    # Not supposed to be edited
    max_text_length: 2000

zotero:
    # See your Zotero profile settings: https://www.zotero.org/settings/keys
    library_id: ???
    api_token: ???
    ignored_collections: []

# Feel free to adjust the text-acronym matches used to parse venues from
# the metadata of articles
venues:
    'international conference on computer vision': 'ICCV'
    'computer vision and pattern recognition': 'CVPR'
    'european conference on computer vision': 'ECCV'
    'asian conference on computer vision': 'ACCV'
    'nips': 'NeurIPS'
    'neural information processing systems': 'NeurIPS'
    'british machine vision conference': 'BMVC'
    'international conference on 3d vision': '3DV'
    'international conference on learning representations': 'ICLR'
    'international conference on machine learning': 'ICML'
    'transactions on pattern analysis and machine intelligence': 'TPAMI'
    'international journal of computer vision': 'IJCV'
    'computer vision and image understanding': 'CVIU'
    'transactions on graphics': 'TOG'
    'international conference on computer graphics and interactive techniques': 'SIGGRAPH'
    'winter conference on applications of computer vision': 'WACV'
